In [4]:
import numpy as np

In [9]:
lending_co_data_numeric_1 = np.loadtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data.csv", delimiter = ',')

In [10]:
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [22]:
lending_co_data_numeric_2 = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data.csv", delimiter = ',')

In [23]:
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [13]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [35]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';')

In [36]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [38]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';', dtype = str)

In [39]:
lending_co_data_numeric_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [40]:
lending_co_data_numeric_NAN[0,0] + lending_co_data_numeric_NAN[0,1]

'200040'

In [41]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';')

In [42]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [44]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';',
                                           skip_footer = 2)
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [50]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';',
                                           usecols =(0,1,2))
lending_co_data_numeric_NAN

array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [  nan,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]])

In [51]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';',
                                           usecols =(2,0,1))
lending_co_data_numeric_NAN

array([[ 365., 2000.,   40.],
       [ 365., 2000.,   40.],
       [ 365., 1000.,   40.],
       ...,
       [ 365.,   nan,   40.],
       [ 365., 1000.,   40.],
       [ 365., 2000.,   40.]])

In [52]:
lending_co_data_numeric_NAN = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';',
                                           usecols =(0,1,2), skip_header = 2, skip_footer = 2)
lending_co_data_numeric_NAN

array([[1000.,   40.,  365.],
       [2000.,   40.,  365.],
       [2000.,   50.,  365.],
       ...,
       [2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [  nan,   40.,  365.]])

In [61]:
lending_co_data_numeric_5,lending_co_data_numeric_0,lending_co_data_numeric_1 = np.genfromtxt("C:/Users/acer/Desktop/My SQL/CSV files in pandas/Lending-Company-Numeric-Data-NAN.csv",
                                            delimiter = ';',
                                           usecols =(0,1,2), skip_header = 2, skip_footer = 2, unpack = True)
print(lending_co_data_numeric_5)
print(lending_co_data_numeric_0)
print(lending_co_data_numeric_1)

[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]
[365. 365. 365. ... 365. 365. 365.]


In [56]:
lending_co_data_numeric_5

array([1000., 2000., 2000., ..., 2000., 2000.,   nan])

In [57]:
lending_co_data_numeric_0

array([40., 40., 50., ..., 40., 40., 40.])

In [58]:
lending_co_data_numeric_1


array([365., 365., 365., ..., 365., 365., 365.])